/* =============================================
   CORTE DEL SOLE — i18n engine
   ============================================= */
(function () {
'use strict';

/* ── LINGUE DISPONIBILI ── */
const LANGS = [
  { code: 'it', flag: '🇮🇹', label: 'IT' },
  { code: 'en', flag: '🇬🇧', label: 'EN' },
  { code: 'de', flag: '🇩🇪', label: 'DE' },
  { code: 'fr', flag: '🇫🇷', label: 'FR' },
  { code: 'es', flag: '🇪🇸', label: 'ES' },
];

/* ── GLOSSARIO INGREDIENTI (ordinato dal più lungo al più corto) ── */
const ING = {
  en: {
    'cipolla brasata nel Valpolicella': 'onion braised in Valpolicella wine',
    'prosciutto crudo di Soave': 'Soave cured ham',
    'prosciutto crudo di Parma': 'Parma cured ham',
    'glassa all\'aceto balsamico': 'balsamic vinegar glaze',
    'granella di pistacchi': 'crushed pistachios',
    'zucchine e melanzane grigliate': 'grilled courgettes and aubergines',
    'code di mazzancolla': 'king prawn tails',
    'straccetti di pollo grigliati': 'grilled chicken strips',
    'champignons freschi': 'fresh mushrooms',
    'melanzane grigliate': 'grilled aubergines',
    'melanzane al forno': 'oven-baked aubergines',
    'melanzane fritte': 'fried aubergines',
    'zucchine grigliate': 'grilled courgettes',
    'funghi trifolati': 'sautéed mushrooms',
    'funghi porcini': 'porcini mushrooms',
    'funghi chiodini': 'honey mushrooms',
    'pomodorini confit': 'confit cherry tomatoes',
    'pomodori secchi': 'sun-dried tomatoes',
    'olive nere greche': 'Greek black olives',
    'peperoni grigliati': 'grilled peppers',
    'salsiccia dolce': 'sweet Italian sausage',
    'salamino piccante': 'spicy salami',
    'gorgonzola dolce': 'mild gorgonzola',
    'pancetta affumicata': 'smoked bacon',
    'provola affumicata': 'smoked provola',
    'bufala campana': 'buffalo mozzarella',
    'burrata pugliese': 'Puglian burrata',
    'prosciutto cotto': 'cooked ham',
    'prosciutto crudo': 'cured ham',
    'crema di tartufo': 'truffle cream',
    'crema al parmigiano': 'parmesan cream',
    'pesto genovese': 'Genovese pesto',
    'salmone affumicato': 'smoked salmon',
    'tonno affumicato': 'smoked tuna',
    'Grana grattugiato': 'grated Grana Padano',
    'scaglie di Grana': 'Grana Padano shavings',
    'cialda di Grana': 'Grana Padano crisp',
    'cipolla rossa': 'red onion',
    'radicchio rosso': 'red radicchio',
    'insalata verde': 'green salad',
    'aceto balsamico': 'balsamic vinegar',
    'pesce spada': 'swordfish',
    'anelli di calamaro': 'squid rings',
    'julienne di verdure croccanti': 'crispy vegetable julienne',
    'ricotta salata': 'salted ricotta',
    'gnocco fritto': 'fried gnocco bread',
    'pomodorini': 'cherry tomatoes',
    'olive greche': 'Greek olives',
    'champignons': 'button mushrooms',
    'melanzane': 'aubergines',
    'zucchine': 'courgettes',
    'radicchio': 'radicchio',
    'capperi': 'capers',
    'acciughe': 'anchovies',
    'gamberetti': 'prawns',
    'carciofi': 'artichokes',
    'origano': 'oregano',
    'basilico': 'basil',
    'rucola': 'rocket',
    'patate': 'potatoes',
    'ricotta': 'ricotta',
    'bresaola': 'bresaola',
    'mortadella': 'mortadella',
    'würstel': 'frankfurters',
    'würstel': 'frankfurters',
    'stracchino': 'stracchino',
    'philadelphia': 'cream cheese',
    'Philadelphia': 'cream cheese',
    'giardiniera': 'pickled vegetables',
    'valeriana': 'lamb\'s lettuce',
    'carote': 'carrots',
    'maionese': 'mayonnaise',
    'mais': 'sweetcorn',
    'olive': 'olives',
    'vongole': 'clams',
    'salmone': 'salmon',
    'tonno': 'tuna',
    'guanciale': 'guanciale',
    'rosmarino': 'rosemary',
    'speck': 'speck',
    'porro': 'leek',
    'noci': 'walnuts',
    'briè': 'brie',
    'mozzarella': 'mozzarella',
    'pomodoro': 'tomato sauce',
    'Asiago': 'Asiago',
    'Grana': 'Grana Padano',
  },
  de: {
    'cipolla brasata nel Valpolicella': 'in Valpolicella-Wein geschmorte Zwiebel',
    'prosciutto crudo di Soave': 'Soave-Rohschinken',
    'prosciutto crudo di Parma': 'Parmaschinken',
    'glassa all\'aceto balsamico': 'Balsamico-Glasur',
    'granella di pistacchi': 'gehackte Pistazien',
    'zucchine e melanzane grigliate': 'gegrillte Zucchini und Auberginen',
    'code di mazzancolla': 'Garnelenschwänze',
    'straccetti di pollo grigliati': 'gegrillte Hähnchenstreifen',
    'champignons freschi': 'frische Champignons',
    'melanzane grigliate': 'gegrillte Auberginen',
    'melanzane al forno': 'ofengebackene Auberginen',
    'melanzane fritte': 'frittierte Auberginen',
    'zucchine grigliate': 'gegrillte Zucchini',
    'funghi trifolati': 'gebratene Pilze',
    'funghi porcini': 'Steinpilze',
    'funghi chiodini': 'Honigpilze',
    'pomodorini confit': 'Confit-Kirschtomaten',
    'pomodori secchi': 'getrocknete Tomaten',
    'olive nere greche': 'griechische schwarze Oliven',
    'peperoni grigliati': 'gegrillte Paprika',
    'salsiccia dolce': 'milde Bratwurst',
    'salamino piccante': 'pikante Salami',
    'gorgonzola dolce': 'milder Gorgonzola',
    'pancetta affumicata': 'geräucherter Speck',
    'provola affumicata': 'geräucherte Provola',
    'bufala campana': 'Büffelmozzarella',
    'burrata pugliese': 'apulische Burrata',
    'prosciutto cotto': 'gekochter Schinken',
    'prosciutto crudo': 'Rohschinken',
    'crema di tartufo': 'Trüffelcreme',
    'crema al parmigiano': 'Parmesancreme',
    'pesto genovese': 'Pesto alla Genovese',
    'salmone affumicato': 'geräucherter Lachs',
    'tonno affumicato': 'geräucherter Thunfisch',
    'Grana grattugiato': 'geriebener Grana Padano',
    'scaglie di Grana': 'Grana-Padano-Späne',
    'cialda di Grana': 'Grana-Padano-Chip',
    'cipolla rossa': 'rote Zwiebel',
    'radicchio rosso': 'roter Radicchio',
    'insalata verde': 'grüner Salat',
    'aceto balsamico': 'Balsamico-Essig',
    'pesce spada': 'Schwertfisch',
    'anelli di calamaro': 'Tintenfischringe',
    'julienne di verdure croccanti': 'knusprige Gemüsejulienne',
    'ricotta salata': 'gesalzene Ricotta',
    'gnocco fritto': 'frittiertes Gnocco-Brot',
    'pomodorini': 'Kirschtomaten',
    'olive greche': 'griechische Oliven',
    'champignons': 'Champignons',
    'melanzane': 'Auberginen',
    'zucchine': 'Zucchini',
    'radicchio': 'Radicchio',
    'capperi': 'Kapern',
    'acciughe': 'Sardellen',
    'gamberetti': 'Garnelen',
    'carciofi': 'Artischocken',
    'origano': 'Oregano',
    'basilico': 'Basilikum',
    'rucola': 'Rucola',
    'patate': 'Kartoffeln',
    'ricotta': 'Ricotta',
    'bresaola': 'Bresaola',
    'mortadella': 'Mortadella',
    'würstel': 'Würstchen',
    'stracchino': 'Stracchino',
    'philadelphia': 'Frischkäse',
    'Philadelphia': 'Frischkäse',
    'giardiniera': 'eingelegtes Gemüse',
    'valeriana': 'Feldsalat',
    'carote': 'Karotten',
    'maionese': 'Mayonnaise',
    'mais': 'Mais',
    'olive': 'Oliven',
    'vongole': 'Venusmuscheln',
    'salmone': 'Lachs',
    'tonno': 'Thunfisch',
    'guanciale': 'Guanciale',
    'rosmarino': 'Rosmarin',
    'speck': 'Speck',
    'porro': 'Lauch',
    'noci': 'Walnüsse',
    'briè': 'Brie',
    'mozzarella': 'Mozzarella',
    'pomodoro': 'Tomatensauce',
    'Asiago': 'Asiago',
    'Grana': 'Grana Padano',
  },
  fr: {
    'cipolla brasata nel Valpolicella': 'oignon braisé au Valpolicella',
    'prosciutto crudo di Soave': 'jambon cru de Soave',
    'prosciutto crudo di Parma': 'jambon de Parme',
    'glassa all\'aceto balsamico': 'glaçage à l\'aceto balsamico',
    'granella di pistacchi': 'éclats de pistaches',
    'zucchine e melanzane grigliate': 'courgettes et aubergines grillées',
    'code di mazzancolla': 'queues de gambas',
    'straccetti di pollo grigliati': 'lanières de poulet grillé',
    'champignons freschi': 'champignons frais',
    'melanzane grigliate': 'aubergines grillées',
    'melanzane al forno': 'aubergines au four',
    'melanzane fritte': 'aubergines frites',
    'zucchine grigliate': 'courgettes grillées',
    'funghi trifolati': 'champignons sautés',
    'funghi porcini': 'cèpes',
    'funghi chiodini': 'armillaires',
    'pomodorini confit': 'tomates cerises confites',
    'pomodori secchi': 'tomates séchées',
    'olive nere greche': 'olives noires grecques',
    'peperoni grigliati': 'poivrons grillés',
    'salsiccia dolce': 'saucisse douce',
    'salamino piccante': 'salami épicé',
    'gorgonzola dolce': 'gorgonzola doux',
    'pancetta affumicata': 'lardons fumés',
    'provola affumicata': 'provola fumée',
    'bufala campana': 'mozzarella de bufflonne',
    'burrata pugliese': 'burrata des Pouilles',
    'prosciutto cotto': 'jambon cuit',
    'prosciutto crudo': 'jambon cru',
    'crema di tartufo': 'crème de truffe',
    'crema al parmigiano': 'crème de parmesan',
    'pesto genovese': 'pesto à la génoise',
    'salmone affumicato': 'saumon fumé',
    'tonno affumicato': 'thon fumé',
    'Grana grattugiato': 'Grana Padano râpé',
    'scaglie di Grana': 'copeaux de Grana Padano',
    'cialda di Grana': 'tuile de Grana Padano',
    'cipolla rossa': 'oignon rouge',
    'radicchio rosso': 'radicchio rouge',
    'insalata verde': 'salade verte',
    'aceto balsamico': 'vinaigre balsamique',
    'pesce spada': 'espadon',
    'anelli di calamaro': 'anneaux de calamar',
    'julienne di verdure croccanti': 'julienne de légumes croquants',
    'ricotta salata': 'ricotta salée',
    'gnocco fritto': 'gnocco frit',
    'pomodorini': 'tomates cerises',
    'olive greche': 'olives grecques',
    'champignons': 'champignons',
    'melanzane': 'aubergines',
    'zucchine': 'courgettes',
    'radicchio': 'radicchio',
    'capperi': 'câpres',
    'acciughe': 'anchois',
    'gamberetti': 'crevettes',
    'carciofi': 'artichauts',
    'origano': 'origan',
    'basilico': 'basilic',
    'rucola': 'roquette',
    'patate': 'pommes de terre',
    'ricotta': 'ricotta',
    'bresaola': 'bresaola',
    'mortadella': 'mortadelle',
    'würstel': 'saucisses de Francfort',
    'stracchino': 'stracchino',
    'philadelphia': 'fromage frais',
    'Philadelphia': 'fromage frais',
    'giardiniera': 'légumes marinés',
    'valeriana': 'mâche',
    'carote': 'carottes',
    'maionese': 'mayonnaise',
    'mais': 'maïs',
    'olive': 'olives',
    'vongole': 'palourdes',
    'salmone': 'saumon',
    'tonno': 'thon',
    'guanciale': 'guanciale',
    'rosmarino': 'romarin',
    'speck': 'speck',
    'porro': 'poireau',
    'noci': 'noix',
    'briè': 'brie',
    'mozzarella': 'mozzarella',
    'pomodoro': 'sauce tomate',
    'Asiago': 'Asiago',
    'Grana': 'Grana Padano',
  },
  es: {
    'cipolla brasata nel Valpolicella': 'cebolla braseada en Valpolicella',
    'prosciutto crudo di Soave': 'jamón curado de Soave',
    'prosciutto crudo di Parma': 'jamón de Parma',
    'glassa all\'aceto balsamico': 'glaseado de vinagre balsámico',
    'granella di pistacchi': 'granillo de pistachos',
    'zucchine e melanzane grigliate': 'calabacines y berenjenas a la plancha',
    'code di mazzancolla': 'colas de langostino',
    'straccetti di pollo grigliati': 'tiras de pollo a la plancha',
    'champignons freschi': 'champiñones frescos',
    'melanzane grigliate': 'berenjenas a la plancha',
    'melanzane al forno': 'berenjenas al horno',
    'melanzane fritte': 'berenjenas fritas',
    'zucchine grigliate': 'calabacines a la plancha',
    'funghi trifolati': 'champiñones salteados',
    'funghi porcini': 'setas porcini',
    'funghi chiodini': 'setas de miel',
    'pomodorini confit': 'tomatitos cherry confitados',
    'pomodori secchi': 'tomates secos',
    'olive nere greche': 'aceitunas negras griegas',
    'peperoni grigliati': 'pimientos a la plancha',
    'salsiccia dolce': 'salchicha dulce',
    'salamino piccante': 'salami picante',
    'gorgonzola dolce': 'gorgonzola suave',
    'pancetta affumicata': 'bacon ahumado',
    'provola affumicata': 'provola ahumada',
    'bufala campana': 'mozzarella de búfala',
    'burrata pugliese': 'burrata de Apulia',
    'prosciutto cotto': 'jamón cocido',
    'prosciutto crudo': 'jamón crudo',
    'crema di tartufo': 'crema de trufa',
    'crema al parmigiano': 'crema de parmesano',
    'pesto genovese': 'pesto genovés',
    'salmone affumicato': 'salmón ahumado',
    'tonno affumicato': 'atún ahumado',
    'Grana grattugiato': 'Grana Padano rallado',
    'scaglie di Grana': 'lascas de Grana Padano',
    'cialda di Grana': 'galleta de Grana Padano',
    'cipolla rossa': 'cebolla roja',
    'radicchio rosso': 'radicchio rojo',
    'insalata verde': 'ensalada verde',
    'aceto balsamico': 'vinagre balsámico',
    'pesce spada': 'pez espada',
    'anelli di calamaro': 'anillas de calamar',
    'julienne di verdure croccanti': 'juliana de verduras crujientes',
    'ricotta salata': 'ricotta salada',
    'gnocco fritto': 'gnocco frito',
    'pomodorini': 'tomatitos cherry',
    'olive greche': 'aceitunas griegas',
    'champignons': 'champiñones',
    'melanzane': 'berenjenas',
    'zucchine': 'calabacines',
    'radicchio': 'radicchio',
    'capperi': 'alcaparras',
    'acciughe': 'anchoas',
    'gamberetti': 'gambas',
    'carciofi': 'alcachofas',
    'origano': 'orégano',
    'basilico': 'albahaca',
    'rucola': 'rúcula',
    'patate': 'patatas',
    'ricotta': 'ricotta',
    'bresaola': 'bresaola',
    'mortadella': 'mortadela',
    'würstel': 'salchichas',
    'stracchino': 'stracchino',
    'philadelphia': 'queso crema',
    'Philadelphia': 'queso crema',
    'giardiniera': 'encurtidos',
    'valeriana': 'canónigos',
    'carote': 'zanahorias',
    'maionese': 'mayonesa',
    'mais': 'maíz',
    'olive': 'aceitunas',
    'vongole': 'almejas',
    'salmone': 'salmón',
    'tonno': 'atún',
    'guanciale': 'guanciale',
    'rosmarino': 'romero',
    'speck': 'speck',
    'porro': 'puerro',
    'noci': 'nueces',
    'briè': 'brie',
    'mozzarella': 'mozzarella',
    'pomodoro': 'salsa de tomate',
    'Asiago': 'Asiago',
    'Grana': 'Grana Padano',
  }
};

/* ── TESTI UI ── */
const T = {
  it: {
    /* navbar */
    'nav.doughs':   'Impasti',
    'nav.about':    'Chi siamo',
    'nav.menu':     'Menu',
    'nav.gallery':  'Galleria',
    'nav.terrace':  'Terrazza',
    'nav.contacts': 'Contatti',
    'nav.book':     'Prenota',
    /* hero index */
    'hero.eyebrow': 'Costeggiola · Verona · Dal 2002',
    'hero.h1':      'Pizze e cucina',
    'hero.h1em':    'fatte in casa',
    'hero.sub':     'Impasti a lenta lievitazione, ingredienti freschi selezionati giorno per giorno. Un\'esperienza gastronomica autentica nel cuore delle colline del Soave.',
    'hero.btnMenu': 'Scopri il Menu',
    'hero.btnBook': 'Prenota un tavolo',
    'hero.scroll':  'Scopri',
    /* impasti */
    'imp.label':   'Arte bianca',
    'imp.h2':      'Sei impasti,',
    'imp.h2em':    'una sola passione',
    'imp.lead':    'Ogni impasto nasce da farine selezionate e maturazioni lente. Sei proposte, un\'unica filosofia.',
    'imp.1.desc':  'Bilanciata miscela di farine attentamente selezionate, lievitazione minima di 48 ore. La base di tutto: croccante sotto, morbida dentro, digeribile.',
    'imp.1.tag':   'La Base',
    'imp.2.desc':  'Farina integrale arricchita con avena, segale, farro, grano saraceno, orzo e germe di grano. Più fibre, più sapore, più carattere.',
    'imp.2.tag':   'Benessere',
    'imp.3.desc':  'Pasta morbida e sottile con cornicione alto e alveolato, lunga maturazione. La pizza italiana per antonomasia, nel rispetto della tradizione partenopea.',
    'imp.3.tag':   'Tradizione',
    'imp.4.desc':  'Mix di farine di frumento, soia e riso con idratazione all\'80%. Croccante fuori, soffice dentro, leggerissima e altamente digeribile.',
    'imp.4.tag':   'Leggerissima',
    'imp.5.desc':  'Nessun lievito o agente lievitante: solo acqua e farine macinate a pietra per una fermentazione naturale. Ideale per chi è sensibile al lievito.',
    'imp.5.tag':   'Senza Lievito',
    'imp.6.desc':  'Impasto certificato SCHAR: farina di riso, amido di patate e farina di semi di carrube, senza lattosio. Pensato con cura per i nostri clienti celiaci o allergici al glutine.',
    'imp.6.tag':   'Celiachia OK',
    /* chi siamo */
    'cs.label': 'Chi siamo',
    'cs.h2':    'Una cucina che parla di',
    'cs.h2em':  'passione',
    'cs.quote': '"Se amate la pizza in ogni sua forma, dimensione e aspetto, siamo fatti esattamente per voi."',
    'cs.p1':    'Tutto ciò che arriva in tavola è preparato con cura, da mani che conoscono la differenza tra fare le cose in fretta e farle bene.',
    'cs.p2':    'Dal 2002 a Costeggiola, una storia di famiglia costruita attorno al gusto autentico e alla qualità degli ingredienti.',
    'cs.f1t':   'Tutto fatto in casa',
    'cs.f1d':   'Pizze, cucina, pasta e dolci. Nessun prodotto industriale.',
    'cs.f2t':   'Menu sempre aggiornato',
    'cs.f2d':   'Consulta il menu online e ordina via telefono o WhatsApp.',
    'cs.f3t':   'Ingredienti freschi',
    'cs.f3d':   'Selezione attenta, stagione per stagione, filiera corta.',
    'cs.v1':    'Le nostre pizze',
    'cs.v2':    'Ingredienti freschi',
    'cs.v3':    'Il nostro locale',
    /* menu preview */
    'mn.label':    'Il nostro menu',
    'mn.h2':       'Cosa portiamo',
    'mn.h2em':     'in tavola',
    'mn.tab1':     'Pizze',
    'mn.tab2':     'Cucina',
    'mn.tab3':     'Dolci & Altro',
    'mn.ph1':      'Pizze',
    'mn.ph2':      'Cucina',
    'mn.ph3':      'Dolci & Altro',
    /* menu item desc (index preview) */
    'mi.margherita':    'Pomodoro, mozzarella',
    'mi.diavola':       'Pomodoro, mozzarella, capperi, salamino piccante',
    'mi.4f':            'Pomodoro, mozzarella, Asiago, gorgonzola, Monte Veronese',
    'mi.capricciosa':   'Prosciutto cotto, funghi, carciofi, olive nere greche',
    'mi.vegetariana':   'Melanzane e zucchine grigliate, radicchio, pomodorini, patate',
    'mi.corte':         'Asiago, carciofi, funghi chiodini, salamino piccante',
    'mi.tartufata':     'Crema di tartufo, porcini, philadelphia, prosciutto crudo',
    'mi.pinsa':         'Mix di farine speciali, 80% idratazione, croccante e leggerissima',
    'mi.tagliere':      'Con gnocco fritto e giardiniera',
    'mi.piovra':        'Con crema al parmigiano, basilico e pomodorini confit',
    'mi.spaghetti':     'Aglio, olio, peperoncino, vongole e pomodorini',
    'mi.tagliata':      'Con rucola e scaglie di Grana',
    'mi.costata':       'Alla griglia, circa 500g',
    'mi.paella':        'Su prenotazione',
    'mi.dolci':         'Chiedere al personale per la proposta del giorno',
    'mi.vini':          'Soave classico, Valpolicella, Amarone — selezione locale',
    /* menu full link */
    'mn.viewFull': 'Vedi menu completo →',
    'mn.note':     'Prezzi indicativi. Il menu completo con tutti i dettagli è disponibile sulla pagina dedicata.',
    /* galleria */
    'gal.label': 'Momenti dal locale',
    'gal.h2':    'La nostra',
    'gal.h2em':  'galleria',
    'gal.c1':    'Pizza con burrata e gamberi',
    'gal.c2':    'Ingredienti del giorno',
    'gal.c3':    'Il forno a legna',
    'gal.c4':    'Dolci fatti in casa',
    'gal.c5':    'Le colline del Soave al tramonto',
    'gal.c6':    'La nostra terrazza estiva',
    /* terrazza */
    'ter.label': 'Estate a Costeggiola',
    'ter.h2':    'Cena in',
    'ter.h2em':  'terrazza',
    'ter.lead':  'Nei mesi più caldi, goditi la pizza all\'aperto nella nostra terrazza esterna. Un\'atmosfera unica tra le colline del Soave, il profumo del vino e il calore della cucina artigianale.',
    'ter.btn':   'Prenota il tuo Tavolo',
    'ter.s1':    'Impasti artigianali',
    'ter.s2':    'Pizze in menu',
    'ter.s3':    'Anni di esperienza',
    'ter.s4':    'Terrazza esterna',
    /* recensioni */
    'rev.label': 'Cosa dicono di noi',
    'rev.h2':    'Le parole dei',
    'rev.h2em':  'nostri ospiti',
    'rev.q1':    '"La pizza napoletana era perfetta — cornicione alto, ingredienti freschi. Un locale autentico che sa il fatto suo. Torneremo sicuramente!"',
    'rev.q2':    '"Finalmente una pizzeria che prende sul serio il senza glutine. Menu ampio e buonissimo. Ci torno con tutta la famiglia."',
    'rev.q3':    '"La pinsa romana è una scoperta. Leggerissima e croccante al punto giusto. Ambiente accogliente, personale gentile e professionale."',
    'rev.ta':    '★ Leggi tutte le recensioni su TripAdvisor',
    /* contatti */
    'con.label':  'Vieni a trovarci',
    'con.h2':     'Dove siamo &',
    'con.h2em':   'come contattarci',
    'con.phone':  'Telefono',
    'con.addr':   'Indirizzo',
    'con.email':  'Email',
    'con.hours':  'Orari di apertura',
    'con.monTue': 'Lunedì – Martedì',
    'con.wedFri': 'Mercoledì – Venerdì',
    'con.sat':    'Sabato',
    'con.sun':    'Domenica',
    'con.closed': 'Chiuso',
    'con.note':   '* Orari indicativi, chiama per conferma',
    'con.call':   'Chiama ora',
    'con.today':  'Oggi',
    'con.open':   'Aperto ora',
    'con.closednow': 'Chiuso ora',
    /* footer */
    'ft.tagline': 'Dal 2002, una cucina che rispetta gli ingredienti e onora la tradizione. Nel cuore del Soave.',
    'ft.nav':     'Navigazione',
    'ft.follow':  'Seguici',
    'ft.home':    'Home',
    'ft.doughs':  'I nostri impasti',
    'ft.about':   'Chi siamo',
    'ft.menuFull':'Menu completo',
    'ft.gallery': 'Galleria',
    'ft.terrace': 'Terrazza',
    'ft.contacts':'Contatti',
    'ft.copy':    '© 2026 Ristorante Pizzeria Corte del Sole · Via Costeggiola 38, Costeggiola (VR)',
    'ft.love':    'Con ♥ nel Soave',
    /* menu.html hero */
    'mh.label':   'Pizzeria Ristorante · Costeggiola (VR)',
    'mh.home':    'Home',
    'mh.h1':      'Il nostro',
    'mh.h1em':    'menu completo',
    'mh.sub':     'Impasti artigianali a lenta lievitazione, ingredienti freschi selezionati e ricette curate con passione. Dal 2002 nel cuore del Soave.',
    'mh.btnBook': 'Prenota un tavolo',
    'mh.btnWa':   'WhatsApp',
    /* menu.html nav tabs */
    'mt.classiche':   'Classiche',
    'mt.nostre':      'Le Nostre',
    'mt.bianche':     'Bianche',
    'mt.glutenfree':  'Senza Glutine',
    'mt.cucina':      'Cucina',
    'mt.insalate':    'Insalate',
    'mt.dolci':       'Dolci & Bibite',
    'mt.vini':        'Vini',
    /* menu.html sezioni */
    'ms.1label': '1 — Pizze',
    'ms.1h2':    'Pizze',
    'ms.1em':    'Classiche',
    'ms.1lead':  'Le basi della nostra arte bianca — impasto napoletano a 48 ore di maturazione, ingredienti selezionati con cura.',
    'ms.2label': '2 — Pizze della casa',
    'ms.2h2':    'Le Nostre',
    'ms.2em':    'Pizze',
    'ms.2lead':  'Creazioni originali nate dalla fantasia dei nostri pizzaioli — ognuna racconta una storia di sapori e territorio.',
    'ms.3label': '3 — Senza pomodoro',
    'ms.3h2':    'Pizze',
    'ms.3em':    'Bianche',
    'ms.3lead':  'Senza pomodoro — la base neutra esalta formaggi, affettati e ingredienti di eccellenza in tutta la loro complessità.',
    'ms.4label': '4 — Senza Glutine',
    'ms.4h2':    'Pizze',
    'ms.4em':    'Senza Glutine',
    'ms.4lead':  'Non un ripensamento — una scelta curata dedicata a chi ha intolleranze celiache. Stesso gusto, stessa cura.',
    'ms.4info':  '<strong>Impasto SCHAR</strong> · farina di riso, amido di patate, farina di semi di carrube · naturalmente senza lattosio. Il prezzo è già comprensivo dell\'impasto senza glutine.',
    'ms.5label': '5 — Cucina',
    'ms.5h2':    'La nostra',
    'ms.5em':    'Cucina',
    'ms.5lead':  'Tutto preparato in casa, ogni giorno. Dalle materie prime alla tavola, senza compromessi.',
    'ms.5note':  'Cucina aperta Mer–Dom · 12:00–14:00 e 19:00–22:00',
    'ms.5ant':   'Antipasti',
    'ms.5pri':   'Primi Piatti',
    'ms.5sec':   'Secondi Piatti',
    'ms.5baby':  'Menù Baby',
    'ms.5res':   'Su prenotazione: Paella e Sangria — <strong>€ 28,00 a persona</strong>',
    'ms.6label': '6 — Insalate',
    'ms.6h2':    'Insalatone',
    'ms.6em':    '& Contorni',
    'ms.6lead':  'Fresche, abbondanti, pensate come piatto unico — o come accompagnamento perfetto.',
    'ms.6cont':  'Contorni',
    'ms.7label': '7 — Dolci & Bibite',
    'ms.7h2':    'Dolci, Bibite',
    'ms.7em':    '& Caffetteria',
    'ms.7lead':  'Il tocco finale — i nostri dolci fatti in casa ogni giorno, accompagnati da birre artigianali e caffetteria.',
    'ms.7dolci': 'Dolci',
    'ms.7bib':   'Bibite & Birre',
    'ms.7caff':  'Caffetteria & Digestivi',
    'ms.8label': '8 — Carta dei Vini',
    'ms.8h2':    'Vini del',
    'ms.8em':    'Territorio',
    'ms.8lead':  'Una selezione curata di vini veneti — Soave, Valpolicella, Amarone — e spumanti locali per accompagnare ogni pasto.',
    'ms.8sp':    'Spumanti',
    'ms.8bi':    'Vini Bianchi',
    'ms.8ro':    'Vini Rossi',
    /* adds */
    'add.title':    'Aggiunte & note',
    'add.coperto':  'Coperto',
    'add.box':      'Box asporto',
    'add.mini':     'Pizze mini',
    'add.doppio':   'Doppio impasto',
    'add.patate':   'Patatine fritte',
    /* note finali menu */
    'note.allerg':  '<strong>Allergeni</strong> — I nostri alimenti potrebbero contenere allergeni. Si prega di informare il personale di eventuali allergie o intolleranze alimentari prima di ordinare. Siamo felici di adattare la vostra esperienza.',
    'note.orari':   '<strong>Orari cucina</strong> — 12:00–14:00 e 19:00–22:00 · La cucina potrebbe chiudersi prima a discrezione del personale.',
    'note.prezzi':  '<strong>Prezzi</strong> — I prezzi indicati sono orientativi. Il menu e i prezzi possono variare senza preavviso. Fare riferimento al menu in sala per i prezzi aggiornati.',
    /* footer menu */
    'fm.col':    'Il Menu',
    'fm.home':   'Torna alla Home',
    'fm.cont':   'Contatti',
  },

  en: {
    'nav.doughs':   'Doughs',
    'nav.about':    'About us',
    'nav.menu':     'Menu',
    'nav.gallery':  'Gallery',
    'nav.terrace':  'Terrace',
    'nav.contacts': 'Contacts',
    'nav.book':     'Book',
    'hero.eyebrow': 'Costeggiola · Verona · Since 2002',
    'hero.h1':      'Pizza and cuisine',
    'hero.h1em':    'made from scratch',
    'hero.sub':     'Slow-risen doughs, hand-picked fresh ingredients every day. An authentic culinary experience in the heart of the Soave hills.',
    'hero.btnMenu': 'Explore the Menu',
    'hero.btnBook': 'Book a table',
    'hero.scroll':  'Discover',
    'imp.label':   'The art of dough',
    'imp.h2':      'Six doughs,',
    'imp.h2em':    'one passion',
    'imp.lead':    'Each dough starts with carefully selected flours and slow fermentation. Six options, one philosophy.',
    'imp.1.desc':  'A balanced blend of carefully selected flours, minimum 48-hour rise. The foundation of everything: crispy underneath, soft inside, highly digestible.',
    'imp.1.tag':   'The Base',
    'imp.2.desc':  'Wholemeal flour enriched with oats, rye, spelt, buckwheat, barley and wheat germ. More fibre, more flavour, more character.',
    'imp.2.tag':   'Wellness',
    'imp.3.desc':  'Soft, thin dough with a tall, airy crust and long maturation. The quintessential Italian pizza, true to Neapolitan tradition.',
    'imp.3.tag':   'Tradition',
    'imp.4.desc':  'Blend of wheat, soy and rice flour with 80% hydration. Crispy outside, soft inside, incredibly light and digestible.',
    'imp.4.tag':   'Featherlight',
    'imp.5.desc':  'No yeast or leavening agents — just water and stone-ground flours for natural fermentation. Ideal for those sensitive to yeast.',
    'imp.5.tag':   'Yeast-Free',
    'imp.6.desc':  'SCHAR-certified dough: rice flour, potato starch and carob seed flour, naturally lactose-free. Carefully crafted for our coeliac and gluten-intolerant guests.',
    'imp.6.tag':   'Coeliac-Safe',
    'cs.label': 'About us',
    'cs.h2':    'A kitchen that',
    'cs.h2em':  'passion',
    'cs.quote': '"If you love pizza in every form, size and shape, we are made exactly for you."',
    'cs.p1':    'Everything that reaches your table is prepared with care, by hands that know the difference between doing things quickly and doing them well.',
    'cs.p2':    'Since 2002 in Costeggiola, a family story built around authentic flavour and quality ingredients.',
    'cs.f1t':   'Everything homemade',
    'cs.f1d':   'Pizzas, kitchen dishes, pasta and desserts. No industrial products.',
    'cs.f2t':   'Always up-to-date menu',
    'cs.f2d':   'Browse the menu online and order by phone or WhatsApp.',
    'cs.f3t':   'Fresh ingredients',
    'cs.f3d':   'Careful selection, season by season, short supply chain.',
    'cs.v1':    'Our pizzas',
    'cs.v2':    'Fresh ingredients',
    'cs.v3':    'Our restaurant',
    'mn.label':    'Our menu',
    'mn.h2':       'What we bring',
    'mn.h2em':     'to the table',
    'mn.tab1':     'Pizzas',
    'mn.tab2':     'Kitchen',
    'mn.tab3':     'Desserts & More',
    'mn.ph1':      'Pizzas',
    'mn.ph2':      'Kitchen',
    'mn.ph3':      'Desserts & More',
    'mi.margherita':    'Tomato sauce, mozzarella',
    'mi.diavola':       'Tomato sauce, mozzarella, capers, spicy salami',
    'mi.4f':            'Tomato sauce, mozzarella, Asiago, gorgonzola, Monte Veronese',
    'mi.capricciosa':   'Cooked ham, mushrooms, artichokes, Greek black olives',
    'mi.vegetariana':   'Grilled aubergines and courgettes, radicchio, cherry tomatoes, potatoes',
    'mi.corte':         'Asiago, artichokes, honey mushrooms, spicy salami',
    'mi.tartufata':     'Truffle cream, porcini mushrooms, cream cheese, cured ham',
    'mi.pinsa':         'Special flour blend, 80% hydration, crispy and incredibly light',
    'mi.tagliere':      'With fried gnocco bread and pickled vegetables',
    'mi.piovra':        'With parmesan cream, basil and confit cherry tomatoes',
    'mi.spaghetti':     'Garlic, olive oil, chilli, clams and cherry tomatoes',
    'mi.tagliata':      'With rocket and Grana Padano shavings',
    'mi.costata':       'Grilled, approx. 500g',
    'mi.paella':        'On request',
    'mi.dolci':         'Ask our staff for today\'s selection',
    'mi.vini':          'Soave classico, Valpolicella, Amarone — local selection',
    'mn.viewFull': 'View full menu →',
    'mn.note':     'Indicative prices. The full menu with all details is available on the dedicated page.',
    'gal.label': 'Moments from the restaurant',
    'gal.h2':    'Our',
    'gal.h2em':  'gallery',
    'gal.c1':    'Pizza with burrata and prawns',
    'gal.c2':    'Today\'s ingredients',
    'gal.c3':    'The wood-fired oven',
    'gal.c4':    'Homemade desserts',
    'gal.c5':    'The Soave hills at sunset',
    'gal.c6':    'Our summer terrace',
    'ter.label': 'Summer in Costeggiola',
    'ter.h2':    'Dinner on the',
    'ter.h2em':  'terrace',
    'ter.lead':  'During the warmer months, enjoy your pizza al fresco on our outdoor terrace. A unique atmosphere among the Soave hills, surrounded by the scent of wine and the warmth of artisan cooking.',
    'ter.btn':   'Book Your Table',
    'ter.s1':    'Artisan doughs',
    'ter.s2':    'Pizzas on the menu',
    'ter.s3':    'Years of experience',
    'ter.s4':    'Outdoor terrace',
    'rev.label': 'What our guests say',
    'rev.h2':    'Words from',
    'rev.h2em':  'our guests',
    'rev.q1':    '"The Neapolitan pizza was perfect — tall crust, fresh ingredients. An authentic restaurant that really knows its craft. We will definitely be back!"',
    'rev.q2':    '"Finally a pizzeria that takes gluten-free seriously. A wide menu and absolutely delicious. I\'ll be back with the whole family."',
    'rev.q3':    '"The pinsa romana is a revelation. Light and crispy in all the right ways. A welcoming atmosphere, friendly and professional staff."',
    'rev.ta':    '★ Read all reviews on TripAdvisor',
    'con.label':  'Find us',
    'con.h2':     'Where we are &',
    'con.h2em':   'how to reach us',
    'con.phone':  'Phone',
    'con.addr':   'Address',
    'con.email':  'Email',
    'con.hours':  'Opening hours',
    'con.monTue': 'Monday – Tuesday',
    'con.wedFri': 'Wednesday – Friday',
    'con.sat':    'Saturday',
    'con.sun':    'Sunday',
    'con.closed': 'Closed',
    'con.note':   '* Indicative times, please call to confirm',
    'con.call':   'Call now',
    'con.today':  'Today',
    'con.open':   'Open now',
    'con.closednow': 'Closed now',
    'ft.tagline': 'Since 2002, a kitchen that honours its ingredients and cherishes tradition. In the heart of Soave.',
    'ft.nav':     'Navigation',
    'ft.follow':  'Follow us',
    'ft.home':    'Home',
    'ft.doughs':  'Our doughs',
    'ft.about':   'About us',
    'ft.menuFull':'Full menu',
    'ft.gallery': 'Gallery',
    'ft.terrace': 'Terrace',
    'ft.contacts':'Contacts',
    'ft.copy':    '© 2026 Ristorante Pizzeria Corte del Sole · Via Costeggiola 38, Costeggiola (VR)',
    'ft.love':    'With ♥ in Soave',
    'mh.label':   'Restaurant Pizzeria · Costeggiola (VR)',
    'mh.home':    'Home',
    'mh.h1':      'Our',
    'mh.h1em':    'full menu',
    'mh.sub':     'Artisan slow-risen doughs, hand-picked fresh ingredients and recipes crafted with passion. Since 2002 in the heart of Soave.',
    'mh.btnBook': 'Book a table',
    'mh.btnWa':   'WhatsApp',
    'mt.classiche':   'Classic',
    'mt.nostre':      'Our Specials',
    'mt.bianche':     'White',
    'mt.glutenfree':  'Gluten-Free',
    'mt.cucina':      'Kitchen',
    'mt.insalate':    'Salads',
    'mt.dolci':       'Desserts & Drinks',
    'mt.vini':        'Wines',
    'ms.1label': '1 — Pizzas',
    'ms.1h2':    'Classic',
    'ms.1em':    'Pizzas',
    'ms.1lead':  'The foundations of our craft — 48-hour Neapolitan dough, carefully selected ingredients.',
    'ms.2label': '2 — House pizzas',
    'ms.2h2':    'Our',
    'ms.2em':    'Signature Pizzas',
    'ms.2lead':  'Original creations born from our pizzaiolos\' creativity — each one tells a story of flavour and terroir.',
    'ms.3label': '3 — No tomato sauce',
    'ms.3h2':    'White',
    'ms.3em':    'Pizzas',
    'ms.3lead':  'No tomato sauce — the neutral base lets the cheeses, charcuterie and premium ingredients shine in all their complexity.',
    'ms.4label': '4 — Gluten-Free',
    'ms.4h2':    'Gluten-Free',
    'ms.4em':    'Pizzas',
    'ms.4lead':  'Not an afterthought — a carefully crafted option for those with coeliac intolerance. Same taste, same care.',
    'ms.4info':  '<strong>SCHAR dough</strong> · rice flour, potato starch, carob seed flour · naturally lactose-free. The gluten-free dough is already included in the listed price.',
    'ms.5label': '5 — Kitchen',
    'ms.5h2':    'Our',
    'ms.5em':    'Kitchen',
    'ms.5lead':  'Everything prepared in-house, every day. From raw ingredients to the table, no compromises.',
    'ms.5note':  'Kitchen open Wed–Sun · 12:00–14:00 and 19:00–22:00',
    'ms.5ant':   'Starters',
    'ms.5pri':   'First Courses',
    'ms.5sec':   'Main Courses',
    'ms.5baby':  'Children\'s Menu',
    'ms.5res':   'On request: Paella and Sangria — <strong>€ 28.00 per person</strong>',
    'ms.6label': '6 — Salads',
    'ms.6h2':    'Large Salads',
    'ms.6em':    '& Sides',
    'ms.6lead':  'Fresh, generous, designed as a main course — or the perfect side dish.',
    'ms.6cont':  'Side Dishes',
    'ms.7label': '7 — Desserts & Drinks',
    'ms.7h2':    'Desserts, Drinks',
    'ms.7em':    '& Coffee',
    'ms.7lead':  'The finishing touch — our homemade desserts prepared daily, paired with craft beers and coffee.',
    'ms.7dolci': 'Desserts',
    'ms.7bib':   'Drinks & Beers',
    'ms.7caff':  'Coffee & Digestifs',
    'ms.8label': '8 — Wine List',
    'ms.8h2':    'Wines of the',
    'ms.8em':    'Territory',
    'ms.8lead':  'A curated selection of Veneto wines — Soave, Valpolicella, Amarone — and local sparkling wines to accompany every meal.',
    'ms.8sp':    'Sparkling Wines',
    'ms.8bi':    'White Wines',
    'ms.8ro':    'Red Wines',
    'add.title':    'Extras & notes',
    'add.coperto':  'Cover charge',
    'add.box':      'Takeaway box',
    'add.mini':     'Mini pizzas',
    'add.doppio':   'Double dough',
    'add.patate':   'French fries',
    'note.allerg':  '<strong>Allergens</strong> — Our food may contain allergens. Please inform our staff of any allergies or food intolerances before ordering. We are happy to adapt your experience.',
    'note.orari':   '<strong>Kitchen hours</strong> — 12:00–14:00 and 19:00–22:00 · The kitchen may close earlier at the staff\'s discretion.',
    'note.prezzi':  '<strong>Prices</strong> — Listed prices are indicative. The menu and prices may change without notice. Please refer to the in-house menu for up-to-date prices.',
    'fm.col':    'The Menu',
    'fm.home':   'Back to Home',
    'fm.cont':   'Contacts',
  },

  de: {
    'nav.doughs':   'Teige',
    'nav.about':    'Über uns',
    'nav.menu':     'Speisekarte',
    'nav.gallery':  'Galerie',
    'nav.terrace':  'Terrasse',
    'nav.contacts': 'Kontakt',
    'nav.book':     'Reservieren',
    'hero.eyebrow': 'Costeggiola · Verona · Seit 2002',
    'hero.h1':      'Pizza und Küche',
    'hero.h1em':    'hausgemacht',
    'hero.sub':     'Langsam gegärte Teige, täglich frisch ausgewählte Zutaten. Ein authentisches Geschmackserlebnis im Herzen der Soave-Hügel.',
    'hero.btnMenu': 'Zur Speisekarte',
    'hero.btnBook': 'Tisch reservieren',
    'hero.scroll':  'Entdecken',
    'imp.label':   'Die Kunst des Teigs',
    'imp.h2':      'Sechs Teige,',
    'imp.h2em':    'eine Leidenschaft',
    'imp.lead':    'Jeder Teig entsteht aus sorgfältig ausgewählten Mehlen und langsamer Reifung. Sechs Angebote, eine Philosophie.',
    'imp.1.desc':  'Ausgewogene Mischung sorgfältig ausgewählter Mehle, mindestens 48 Stunden Gärzeit. Die Basis von allem: knusprig unten, weich innen, gut verträglich.',
    'imp.1.tag':   'Die Basis',
    'imp.2.desc':  'Vollkornmehl angereichert mit Hafer, Roggen, Dinkel, Buchweizen, Gerste und Weizenkeimen. Mehr Ballaststoffe, mehr Geschmack, mehr Charakter.',
    'imp.2.tag':   'Wohlbefinden',
    'imp.3.desc':  'Weicher, dünner Teig mit hohem, luftigem Rand und langer Reifezeit. Die Pizza schlechthin, gemäß der neapolitanischen Tradition.',
    'imp.3.tag':   'Tradition',
    'imp.4.desc':  'Mischung aus Weizen-, Soja- und Reismehl mit 80 % Hydratation. Außen knusprig, innen weich, unglaublich leicht und bekömmlich.',
    'imp.4.tag':   'Federleicht',
    'imp.5.desc':  'Kein Hefe oder Triebmittel — nur Wasser und steinvermahlene Mehle für natürliche Fermentation. Ideal für Hefeintolerante.',
    'imp.5.tag':   'Hefefrei',
    'imp.6.desc':  'SCHAR-zertifizierter Teig: Reismehl, Kartoffelstärke und Johannisbrotkernmehl, von Natur aus laktosefrei. Sorgfältig entwickelt für unsere zöliakiebetroffenen Gäste.',
    'imp.6.tag':   'Glutenfrei',
    'cs.label': 'Über uns',
    'cs.h2':    'Eine Küche, die von',
    'cs.h2em':  'Leidenschaft',
    'cs.quote': '„Wenn Sie Pizza in all ihren Formen lieben, sind wir genau die Richtigen für Sie."',
    'cs.p1':    'Alles, was auf den Tisch kommt, wird mit Sorgfalt zubereitet — von Händen, die den Unterschied kennen zwischen schnell und gut.',
    'cs.p2':    'Seit 2002 in Costeggiola — eine Familiengeschichte rund um echten Geschmack und hochwertige Zutaten.',
    'cs.f1t':   'Alles hausgemacht',
    'cs.f1d':   'Pizzen, Gerichte, Pasta und Desserts. Keine industriellen Produkte.',
    'cs.f2t':   'Stets aktuelles Menü',
    'cs.f2d':   'Speisekarte online einsehen und per Telefon oder WhatsApp bestellen.',
    'cs.f3t':   'Frische Zutaten',
    'cs.f3d':   'Sorgfältige Auswahl, Saison für Saison, kurze Lieferkette.',
    'cs.v1':    'Unsere Pizzen',
    'cs.v2':    'Frische Zutaten',
    'cs.v3':    'Unser Lokal',
    'mn.label':    'Unsere Speisekarte',
    'mn.h2':       'Was wir',
    'mn.h2em':     'auftischen',
    'mn.tab1':     'Pizzen',
    'mn.tab2':     'Küche',
    'mn.tab3':     'Desserts & Mehr',
    'mn.ph1':      'Pizzen',
    'mn.ph2':      'Küche',
    'mn.ph3':      'Desserts & Mehr',
    'mi.margherita':    'Tomatensauce, Mozzarella',
    'mi.diavola':       'Tomatensauce, Mozzarella, Kapern, pikante Salami',
    'mi.4f':            'Tomatensauce, Mozzarella, Asiago, Gorgonzola, Monte Veronese',
    'mi.capricciosa':   'Gekochter Schinken, Pilze, Artischocken, griechische Oliven',
    'mi.vegetariana':   'Gegrillte Auberginen und Zucchini, Radicchio, Kirschtomaten, Kartoffeln',
    'mi.corte':         'Asiago, Artischocken, Honigpilze, pikante Salami',
    'mi.tartufata':     'Trüffelcreme, Steinpilze, Frischkäse, Rohschinken',
    'mi.pinsa':         'Spezielles Mehlgemisch, 80 % Wasseranteil, knusprig und federleicht',
    'mi.tagliere':      'Mit frittiertem Gnocco-Brot und eingelegtem Gemüse',
    'mi.piovra':        'Mit Parmesancreme, Basilikum und Confit-Kirschtomaten',
    'mi.spaghetti':     'Knoblauch, Olivenöl, Chili, Venusmuscheln und Kirschtomaten',
    'mi.tagliata':      'Mit Rucola und Grana-Padano-Spänen',
    'mi.costata':       'Gegrillt, ca. 500 g',
    'mi.paella':        'Auf Vorbestellung',
    'mi.dolci':         'Bitte das Personal nach dem heutigen Angebot fragen',
    'mi.vini':          'Soave classico, Valpolicella, Amarone — lokale Auswahl',
    'mn.viewFull': 'Vollständige Speisekarte →',
    'mn.note':     'Unverbindliche Preise. Die vollständige Speisekarte finden Sie auf der entsprechenden Seite.',
    'gal.label': 'Momente aus dem Restaurant',
    'gal.h2':    'Unsere',
    'gal.h2em':  'Galerie',
    'gal.c1':    'Pizza mit Burrata und Garnelen',
    'gal.c2':    'Zutaten des Tages',
    'gal.c3':    'Der Holzofen',
    'gal.c4':    'Hausgemachte Desserts',
    'gal.c5':    'Die Soave-Hügel im Sonnenuntergang',
    'gal.c6':    'Unsere Sommerterrasse',
    'ter.label': 'Sommer in Costeggiola',
    'ter.h2':    'Abendessen auf der',
    'ter.h2em':  'Terrasse',
    'ter.lead':  'In den wärmeren Monaten genießen Sie Ihre Pizza im Freien auf unserer Außenterrasse. Eine einzigartige Atmosphäre zwischen den Soave-Hügeln, im Duft des Weins und der Wärme der handwerklichen Küche.',
    'ter.btn':   'Tisch reservieren',
    'ter.s1':    'Handwerkliche Teige',
    'ter.s2':    'Pizzen auf der Karte',
    'ter.s3':    'Jahre Erfahrung',
    'ter.s4':    'Außenterrasse',
    'rev.label': 'Was unsere Gäste sagen',
    'rev.h2':    'Die Worte',
    'rev.h2em':  'unserer Gäste',
    'rev.q1':    '„Die neapolitanische Pizza war perfekt — hoher Rand, frische Zutaten. Ein authentisches Lokal, das wirklich weiß, was es tut. Wir kommen bestimmt wieder!"',
    'rev.q2':    '„Endlich eine Pizzeria, die Glutenfrei ernst nimmt. Großes Angebot und wirklich lecker. Ich komme mit der ganzen Familie wieder."',
    'rev.q3':    '„Die Pinsa romana ist eine Entdeckung. Leicht und knusprig genau richtig. Gemütliche Atmosphäre, freundliches und professionelles Personal."',
    'rev.ta':    '★ Alle Bewertungen auf TripAdvisor lesen',
    'con.label':  'Besuchen Sie uns',
    'con.h2':     'Wo wir sind &',
    'con.h2em':   'wie Sie uns erreichen',
    'con.phone':  'Telefon',
    'con.addr':   'Adresse',
    'con.email':  'E-Mail',
    'con.hours':  'Öffnungszeiten',
    'con.monTue': 'Montag – Dienstag',
    'con.wedFri': 'Mittwoch – Freitag',
    'con.sat':    'Samstag',
    'con.sun':    'Sonntag',
    'con.closed': 'Geschlossen',
    'con.note':   '* Unverbindliche Zeiten, bitte telefonisch bestätigen',
    'con.call':   'Jetzt anrufen',
    'con.today':  'Heute',
    'con.open':   'Jetzt geöffnet',
    'con.closednow': 'Jetzt geschlossen',
    'ft.tagline': 'Seit 2002 — eine Küche, die ihre Zutaten respektiert und die Tradition ehrt. Im Herzen von Soave.',
    'ft.nav':     'Navigation',
    'ft.follow':  'Folge uns',
    'ft.home':    'Startseite',
    'ft.doughs':  'Unsere Teige',
    'ft.about':   'Über uns',
    'ft.menuFull':'Vollständige Speisekarte',
    'ft.gallery': 'Galerie',
    'ft.terrace': 'Terrasse',
    'ft.contacts':'Kontakt',
    'ft.copy':    '© 2026 Ristorante Pizzeria Corte del Sole · Via Costeggiola 38, Costeggiola (VR)',
    'ft.love':    'Mit ♥ im Soave',
    'mh.label':   'Ristorante Pizzeria · Costeggiola (VR)',
    'mh.home':    'Startseite',
    'mh.h1':      'Unsere',
    'mh.h1em':    'vollständige Speisekarte',
    'mh.sub':     'Handwerklich langsam gegärte Teige, frisch ausgewählte Zutaten und mit Leidenschaft entwickelte Rezepte. Seit 2002 im Herzen von Soave.',
    'mh.btnBook': 'Tisch reservieren',
    'mh.btnWa':   'WhatsApp',
    'mt.classiche':   'Klassische',
    'mt.nostre':      'Hauskreationen',
    'mt.bianche':     'Weiße',
    'mt.glutenfree':  'Glutenfrei',
    'mt.cucina':      'Küche',
    'mt.insalate':    'Salate',
    'mt.dolci':       'Desserts & Getränke',
    'mt.vini':        'Weine',
    'ms.1label': '1 — Pizzen',
    'ms.1h2':    'Klassische',
    'ms.1em':    'Pizzen',
    'ms.1lead':  'Die Grundlage unseres Handwerks — 48-stündig gereifter neapolitanischer Teig, sorgfältig ausgewählte Zutaten.',
    'ms.2label': '2 — Hauspizzen',
    'ms.2h2':    'Unsere',
    'ms.2em':    'Signature-Pizzen',
    'ms.2lead':  'Originelle Kreationen aus der Fantasie unserer Pizzabäcker — jede erzählt eine Geschichte von Aromen und Herkunft.',
    'ms.3label': '3 — Ohne Tomatensauce',
    'ms.3h2':    'Weiße',
    'ms.3em':    'Pizzen',
    'ms.3lead':  'Ohne Tomatensauce — die neutrale Basis lässt Käse, Aufschnitt und erstklassige Zutaten in voller Komplexität glänzen.',
    'ms.4label': '4 — Glutenfrei',
    'ms.4h2':    'Glutenfreie',
    'ms.4em':    'Pizzen',
    'ms.4lead':  'Keine Nachgedanke — eine sorgfältig entwickelte Option für Menschen mit Zöliakie. Gleicher Geschmack, gleiche Sorgfalt.',
    'ms.4info':  '<strong>SCHAR-Teig</strong> · Reismehl, Kartoffelstärke, Johannisbrotmehl · von Natur aus laktosefrei. Der glutenfreie Teig ist bereits im angegebenen Preis enthalten.',
    'ms.5label': '5 — Küche',
    'ms.5h2':    'Unsere',
    'ms.5em':    'Küche',
    'ms.5lead':  'Alles täglich frisch zubereitet. Vom Rohstoff bis auf den Tisch — ohne Kompromisse.',
    'ms.5note':  'Küche geöffnet Mi–So · 12:00–14:00 und 19:00–22:00',
    'ms.5ant':   'Vorspeisen',
    'ms.5pri':   'Erste Gänge',
    'ms.5sec':   'Hauptgänge',
    'ms.5baby':  'Kindermenü',
    'ms.5res':   'Auf Vorbestellung: Paella und Sangria — <strong>€ 28,00 pro Person</strong>',
    'ms.6label': '6 — Salate',
    'ms.6h2':    'Großsalate',
    'ms.6em':    '& Beilagen',
    'ms.6lead':  'Frisch, üppig — als vollwertiges Gericht oder perfekte Beilage gedacht.',
    'ms.6cont':  'Beilagen',
    'ms.7label': '7 — Desserts & Getränke',
    'ms.7h2':    'Desserts, Getränke',
    'ms.7em':    '& Kaffee',
    'ms.7lead':  'Das krönende Finale — täglich frisch zubereitete Desserts, begleitet von Craft-Bier und Kaffee.',
    'ms.7dolci': 'Desserts',
    'ms.7bib':   'Getränke & Bier',
    'ms.7caff':  'Kaffee & Digestifs',
    'ms.8label': '8 — Weinkarte',
    'ms.8h2':    'Weine der',
    'ms.8em':    'Region',
    'ms.8lead':  'Eine kuratierte Auswahl venetianischer Weine — Soave, Valpolicella, Amarone — und lokale Schaumweine zu jedem Gericht.',
    'ms.8sp':    'Schaumweine',
    'ms.8bi':    'Weißweine',
    'ms.8ro':    'Rotweine',
    'add.title':    'Extras & Hinweise',
    'add.coperto':  'Gedeck',
    'add.box':      'Mitnahme-Box',
    'add.mini':     'Mini-Pizzen',
    'add.doppio':   'Doppelter Teig',
    'add.patate':   'Pommes frites',
    'note.allerg':  '<strong>Allergene</strong> — Unsere Speisen können Allergene enthalten. Bitte informieren Sie das Personal vor der Bestellung über Allergien oder Unverträglichkeiten. Wir passen Ihr Erlebnis gerne an.',
    'note.orari':   '<strong>Küchenzeiten</strong> — 12:00–14:00 und 19:00–22:00 · Die Küche kann nach Ermessen des Personals früher schließen.',
    'note.prezzi':  '<strong>Preise</strong> — Die angegebenen Preise sind Richtwerte. Speisekarte und Preise können sich ohne Vorankündigung ändern. Bitte beachten Sie die aktuelle Karte im Lokal.',
    'fm.col':    'Die Speisekarte',
    'fm.home':   'Zurück zur Startseite',
    'fm.cont':   'Kontakt',
  },

  fr: {
    'nav.doughs':   'Pâtes',
    'nav.about':    'Qui sommes-nous',
    'nav.menu':     'Menu',
    'nav.gallery':  'Galerie',
    'nav.terrace':  'Terrasse',
    'nav.contacts': 'Contact',
    'nav.book':     'Réserver',
    'hero.eyebrow': 'Costeggiola · Vérone · Depuis 2002',
    'hero.h1':      'Pizzas et cuisine',
    'hero.h1em':    'faites maison',
    'hero.sub':     'Pâtes à levée lente, ingrédients frais sélectionnés chaque jour. Une expérience gastronomique authentique au cœur des collines de Soave.',
    'hero.btnMenu': 'Découvrir le Menu',
    'hero.btnBook': 'Réserver une table',
    'hero.scroll':  'Découvrir',
    'imp.label':   'L\'art de la pâte',
    'imp.h2':      'Six pâtes,',
    'imp.h2em':    'une seule passion',
    'imp.lead':    'Chaque pâte naît de farines soigneusement sélectionnées et de fermentations lentes. Six propositions, une seule philosophie.',
    'imp.1.desc':  'Mélange équilibré de farines soigneusement sélectionnées, fermentation minimum 48 heures. La base de tout : croustillante dessous, moelleuse dedans, légère et digeste.',
    'imp.1.tag':   'La Base',
    'imp.2.desc':  'Farine complète enrichie d\'avoine, seigle, épeautre, sarrasin, orge et germe de blé. Plus de fibres, plus de saveur, plus de caractère.',
    'imp.2.tag':   'Bien-être',
    'imp.3.desc':  'Pâte souple et fine avec un bord haut et alvéolé, longue maturation. La pizza italienne par excellence, dans le respect de la tradition napolitaine.',
    'imp.3.tag':   'Tradition',
    'imp.4.desc':  'Mélange de farines de blé, soja et riz avec 80 % d\'hydratation. Croustillante dehors, moelleuse dedans, légère et très digeste.',
    'imp.4.tag':   'Ultra-légère',
    'imp.5.desc':  'Aucune levure ni agent levant — uniquement de l\'eau et des farines moulues sur pierre pour une fermentation naturelle. Idéale pour les sensibles à la levure.',
    'imp.5.tag':   'Sans Levure',
    'imp.6.desc':  'Pâte certifiée SCHAR : farine de riz, amidon de pomme de terre et farine de caroube, naturellement sans lactose. Conçue avec soin pour nos clients cœliaques.',
    'imp.6.tag':   'Sans Gluten',
    'cs.label': 'Qui sommes-nous',
    'cs.h2':    'Une cuisine qui parle de',
    'cs.h2em':  'passion',
    'cs.quote': '« Si vous aimez la pizza sous toutes ses formes, nous sommes faits exactement pour vous. »',
    'cs.p1':    'Tout ce qui arrive à table est préparé avec soin, par des mains qui connaissent la différence entre aller vite et bien faire.',
    'cs.p2':    'Depuis 2002 à Costeggiola — une histoire de famille construite autour de la saveur authentique et de la qualité des ingrédients.',
    'cs.f1t':   'Tout fait maison',
    'cs.f1d':   'Pizzas, cuisine, pâtes et desserts. Aucun produit industriel.',
    'cs.f2t':   'Menu toujours à jour',
    'cs.f2d':   'Consultez le menu en ligne et commandez par téléphone ou WhatsApp.',
    'cs.f3t':   'Ingrédients frais',
    'cs.f3d':   'Sélection rigoureuse, saison après saison, circuit court.',
    'cs.v1':    'Nos pizzas',
    'cs.v2':    'Ingrédients frais',
    'cs.v3':    'Notre restaurant',
    'mn.label':    'Notre menu',
    'mn.h2':       'Ce que nous apportons',
    'mn.h2em':     'à table',
    'mn.tab1':     'Pizzas',
    'mn.tab2':     'Cuisine',
    'mn.tab3':     'Desserts & Autres',
    'mn.ph1':      'Pizzas',
    'mn.ph2':      'Cuisine',
    'mn.ph3':      'Desserts & Autres',
    'mi.margherita':    'Sauce tomate, mozzarella',
    'mi.diavola':       'Sauce tomate, mozzarella, câpres, salami épicé',
    'mi.4f':            'Sauce tomate, mozzarella, Asiago, gorgonzola, Monte Veronese',
    'mi.capricciosa':   'Jambon cuit, champignons, artichauts, olives noires grecques',
    'mi.vegetariana':   'Aubergines et courgettes grillées, radicchio, tomates cerises, pommes de terre',
    'mi.corte':         'Asiago, artichauts, armillaires, salami épicé',
    'mi.tartufata':     'Crème de truffe, cèpes, fromage frais, jambon cru',
    'mi.pinsa':         'Mélange de farines spéciales, 80 % d\'hydratation, croustillante et ultra-légère',
    'mi.tagliere':      'Avec gnocco frit et légumes marinés',
    'mi.piovra':        'Avec crème de parmesan, basilic et tomates cerises confites',
    'mi.spaghetti':     'Ail, huile d\'olive, piment, palourdes et tomates cerises',
    'mi.tagliata':      'Avec roquette et copeaux de Grana Padano',
    'mi.costata':       'Grillée, environ 500 g',
    'mi.paella':        'Sur réservation',
    'mi.dolci':         'Demander au personnel la proposition du jour',
    'mi.vini':          'Soave classico, Valpolicella, Amarone — sélection locale',
    'mn.viewFull': 'Voir le menu complet →',
    'mn.note':     'Prix indicatifs. Le menu complet est disponible sur la page dédiée.',
    'gal.label': 'Moments du restaurant',
    'gal.h2':    'Notre',
    'gal.h2em':  'galerie',
    'gal.c1':    'Pizza burrata et crevettes',
    'gal.c2':    'Les ingrédients du jour',
    'gal.c3':    'Le four à bois',
    'gal.c4':    'Desserts faits maison',
    'gal.c5':    'Les collines de Soave au coucher du soleil',
    'gal.c6':    'Notre terrasse estivale',
    'ter.label': 'L\'été à Costeggiola',
    'ter.h2':    'Dîner en',
    'ter.h2em':  'terrasse',
    'ter.lead':  'Durant les mois les plus chauds, savourez votre pizza en plein air sur notre terrasse extérieure. Une atmosphère unique entre les collines de Soave, le parfum du vin et la chaleur de la cuisine artisanale.',
    'ter.btn':   'Réserver votre table',
    'ter.s1':    'Pâtes artisanales',
    'ter.s2':    'Pizzas à la carte',
    'ter.s3':    'Ans d\'expérience',
    'ter.s4':    'Terrasse extérieure',
    'rev.label': 'Ce que nos clients disent',
    'rev.h2':    'Les mots de',
    'rev.h2em':  'nos clients',
    'rev.q1':    '« La pizza napolitaine était parfaite — bord haut, ingrédients frais. Un restaurant authentique qui sait vraiment ce qu\'il fait. On reviendra ! »',
    'rev.q2':    '« Enfin une pizzeria qui prend le sans gluten au sérieux. Un menu varié et délicieux. J\'y retournerai avec toute la famille. »',
    'rev.q3':    '« La pinsa romana est une vraie découverte. Légère et croustillante exactement comme il faut. Ambiance accueillante, personnel attentionné et professionnel. »',
    'rev.ta':    '★ Lire tous les avis sur TripAdvisor',
    'con.label':  'Venez nous rendre visite',
    'con.h2':     'Où nous sommes &',
    'con.h2em':   'comment nous contacter',
    'con.phone':  'Téléphone',
    'con.addr':   'Adresse',
    'con.email':  'E-mail',
    'con.hours':  'Horaires d\'ouverture',
    'con.monTue': 'Lundi – Mardi',
    'con.wedFri': 'Mercredi – Vendredi',
    'con.sat':    'Samedi',
    'con.sun':    'Dimanche',
    'con.closed': 'Fermé',
    'con.note':   '* Horaires indicatifs, appelez pour confirmation',
    'con.call':   'Appeler maintenant',
    'con.today':  'Aujourd\'hui',
    'con.open':   'Ouvert maintenant',
    'con.closednow': 'Fermé en ce moment',
    'ft.tagline': 'Depuis 2002, une cuisine qui respecte ses ingrédients et honore la tradition. Au cœur de Soave.',
    'ft.nav':     'Navigation',
    'ft.follow':  'Suivez-nous',
    'ft.home':    'Accueil',
    'ft.doughs':  'Nos pâtes',
    'ft.about':   'Qui sommes-nous',
    'ft.menuFull':'Menu complet',
    'ft.gallery': 'Galerie',
    'ft.terrace': 'Terrasse',
    'ft.contacts':'Contact',
    'ft.copy':    '© 2026 Ristorante Pizzeria Corte del Sole · Via Costeggiola 38, Costeggiola (VR)',
    'ft.love':    'Avec ♥ à Soave',
    'mh.label':   'Restaurant Pizzeria · Costeggiola (VR)',
    'mh.home':    'Accueil',
    'mh.h1':      'Notre',
    'mh.h1em':    'menu complet',
    'mh.sub':     'Pâtes artisanales à levée lente, ingrédients frais sélectionnés et recettes élaborées avec passion. Depuis 2002 au cœur de Soave.',
    'mh.btnBook': 'Réserver une table',
    'mh.btnWa':   'WhatsApp',
    'mt.classiche':   'Classiques',
    'mt.nostre':      'Nos Créations',
    'mt.bianche':     'Blanches',
    'mt.glutenfree':  'Sans Gluten',
    'mt.cucina':      'Cuisine',
    'mt.insalate':    'Salades',
    'mt.dolci':       'Desserts & Boissons',
    'mt.vini':        'Vins',
    'ms.1label': '1 — Pizzas',
    'ms.1h2':    'Pizzas',
    'ms.1em':    'Classiques',
    'ms.1lead':  'Les bases de notre art — pâte napolitaine mûrie 48 heures, ingrédients sélectionnés avec soin.',
    'ms.2label': '2 — Pizzas maison',
    'ms.2h2':    'Nos',
    'ms.2em':    'Pizzas Signature',
    'ms.2lead':  'Créations originales nées de l\'imagination de nos pizzaïolos — chacune raconte une histoire de saveurs et de terroir.',
    'ms.3label': '3 — Sans sauce tomate',
    'ms.3h2':    'Pizzas',
    'ms.3em':    'Blanches',
    'ms.3lead':  'Sans sauce tomate — la base neutre met en valeur fromages, charcuteries et ingrédients d\'exception dans toute leur complexité.',
    'ms.4label': '4 — Sans Gluten',
    'ms.4h2':    'Pizzas',
    'ms.4em':    'Sans Gluten',
    'ms.4lead':  'Pas une concession — un choix réfléchi pour les intolérants au gluten. Même goût, même soin.',
    'ms.4info':  '<strong>Pâte SCHAR</strong> · farine de riz, fécule de pomme de terre, farine de caroube · naturellement sans lactose. La pâte sans gluten est déjà incluse dans le prix affiché.',
    'ms.5label': '5 — Cuisine',
    'ms.5h2':    'Notre',
    'ms.5em':    'Cuisine',
    'ms.5lead':  'Tout préparé maison, chaque jour. Des matières premières à l\'assiette, sans compromis.',
    'ms.5note':  'Cuisine ouverte mer–dim · 12h00–14h00 et 19h00–22h00',
    'ms.5ant':   'Entrées',
    'ms.5pri':   'Premiers Plats',
    'ms.5sec':   'Plats Principaux',
    'ms.5baby':  'Menu Enfant',
    'ms.5res':   'Sur réservation : Paella et Sangria — <strong>28,00 € par personne</strong>',
    'ms.6label': '6 — Salades',
    'ms.6h2':    'Grandes Salades',
    'ms.6em':    '& Accompagnements',
    'ms.6lead':  'Fraîches, généreuses, conçues comme plat principal — ou accompagnement parfait.',
    'ms.6cont':  'Accompagnements',
    'ms.7label': '7 — Desserts & Boissons',
    'ms.7h2':    'Desserts, Boissons',
    'ms.7em':    '& Café',
    'ms.7lead':  'La touche finale — nos desserts faits maison chaque jour, accompagnés de bières artisanales et d\'un bon café.',
    'ms.7dolci': 'Desserts',
    'ms.7bib':   'Boissons & Bières',
    'ms.7caff':  'Café & Digestifs',
    'ms.8label': '8 — Carte des Vins',
    'ms.8h2':    'Vins du',
    'ms.8em':    'Territoire',
    'ms.8lead':  'Une sélection curatée de vins vénitiens — Soave, Valpolicella, Amarone — et vins pétillants locaux pour accompagner chaque repas.',
    'ms.8sp':    'Vins Pétillants',
    'ms.8bi':    'Vins Blancs',
    'ms.8ro':    'Vins Rouges',
    'add.title':    'Suppléments & notes',
    'add.coperto':  'Couvert',
    'add.box':      'Boîte à emporter',
    'add.mini':     'Mini-pizzas',
    'add.doppio':   'Double pâte',
    'add.patate':   'Frites',
    'note.allerg':  '<strong>Allergènes</strong> — Nos aliments peuvent contenir des allergènes. Veuillez informer le personnel de toute allergie ou intolérance avant de commander. Nous sommes heureux d\'adapter votre expérience.',
    'note.orari':   '<strong>Horaires cuisine</strong> — 12h00–14h00 et 19h00–22h00 · La cuisine peut fermer plus tôt à la discrétion du personnel.',
    'note.prezzi':  '<strong>Prix</strong> — Les prix indiqués sont indicatifs. Le menu et les prix peuvent changer sans préavis. Veuillez vous référer au menu en salle pour les prix actualisés.',
    'fm.col':    'Le Menu',
    'fm.home':   'Retour à l\'accueil',
    'fm.cont':   'Contact',
  },

  es: {
    'nav.doughs':   'Masas',
    'nav.about':    'Quiénes somos',
    'nav.menu':     'Carta',
    'nav.gallery':  'Galería',
    'nav.terrace':  'Terraza',
    'nav.contacts': 'Contacto',
    'nav.book':     'Reservar',
    'hero.eyebrow': 'Costeggiola · Verona · Desde 2002',
    'hero.h1':      'Pizzas y cocina',
    'hero.h1em':    'hechas en casa',
    'hero.sub':     'Masas de fermentación lenta, ingredientes frescos seleccionados cada día. Una experiencia gastronómica auténtica en el corazón de las colinas del Soave.',
    'hero.btnMenu': 'Descubrir la Carta',
    'hero.btnBook': 'Reservar una mesa',
    'hero.scroll':  'Descubrir',
    'imp.label':   'El arte de la masa',
    'imp.h2':      'Seis masas,',
    'imp.h2em':    'una sola pasión',
    'imp.lead':    'Cada masa nace de harinas cuidadosamente seleccionadas y fermentaciones lentas. Seis propuestas, una sola filosofía.',
    'imp.1.desc':  'Mezcla equilibrada de harinas cuidadosamente seleccionadas, fermentación mínima de 48 horas. La base de todo: crujiente abajo, suave dentro, muy digestible.',
    'imp.1.tag':   'La Base',
    'imp.2.desc':  'Harina integral enriquecida con avena, centeno, espelta, trigo sarraceno, cebada y germen de trigo. Más fibra, más sabor, más carácter.',
    'imp.2.tag':   'Bienestar',
    'imp.3.desc':  'Masa blanda y fina con borde alto y alveolado, larga maduración. La pizza italiana por excelencia, fiel a la tradición napolitana.',
    'imp.3.tag':   'Tradición',
    'imp.4.desc':  'Mezcla de harinas de trigo, soja y arroz con un 80% de hidratación. Crujiente por fuera, suave por dentro, muy ligera y digestible.',
    'imp.4.tag':   'Ligerísima',
    'imp.5.desc':  'Sin levadura ni agentes leudantes: solo agua y harinas molidas a piedra para una fermentación natural. Ideal para quienes son sensibles a la levadura.',
    'imp.5.tag':   'Sin Levadura',
    'imp.6.desc':  'Masa certificada SCHAR: harina de arroz, almidón de patata y harina de semillas de algarrobo, sin lactosa. Elaborada con cuidado para nuestros clientes celíacos.',
    'imp.6.tag':   'Apto Celíacos',
    'cs.label': 'Quiénes somos',
    'cs.h2':    'Una cocina que habla de',
    'cs.h2em':  'pasión',
    'cs.quote': '«Si amáis la pizza en todas sus formas, estamos hechos exactamente para vosotros.»',
    'cs.p1':    'Todo lo que llega a la mesa se prepara con esmero, por manos que conocen la diferencia entre hacer las cosas deprisa y hacerlas bien.',
    'cs.p2':    'Desde 2002 en Costeggiola — una historia familiar construida alrededor del sabor auténtico y la calidad de los ingredientes.',
    'cs.f1t':   'Todo hecho en casa',
    'cs.f1d':   'Pizzas, cocina, pasta y postres. Ningún producto industrial.',
    'cs.f2t':   'Carta siempre actualizada',
    'cs.f2d':   'Consulta la carta online y pide por teléfono o WhatsApp.',
    'cs.f3t':   'Ingredientes frescos',
    'cs.f3d':   'Selección cuidadosa, temporada a temporada, proximidad garantizada.',
    'cs.v1':    'Nuestras pizzas',
    'cs.v2':    'Ingredientes frescos',
    'cs.v3':    'Nuestro local',
    'mn.label':    'Nuestra carta',
    'mn.h2':       'Lo que llevamos',
    'mn.h2em':     'a la mesa',
    'mn.tab1':     'Pizzas',
    'mn.tab2':     'Cocina',
    'mn.tab3':     'Postres & Más',
    'mn.ph1':      'Pizzas',
    'mn.ph2':      'Cocina',
    'mn.ph3':      'Postres & Más',
    'mi.margherita':    'Salsa de tomate, mozzarella',
    'mi.diavola':       'Salsa de tomate, mozzarella, alcaparras, salami picante',
    'mi.4f':            'Salsa de tomate, mozzarella, Asiago, gorgonzola, Monte Veronese',
    'mi.capricciosa':   'Jamón cocido, champiñones, alcachofas, aceitunas negras griegas',
    'mi.vegetariana':   'Berenjenas y calabacines a la plancha, radicchio, tomatitos cherry, patatas',
    'mi.corte':         'Asiago, alcachofas, setas de miel, salami picante',
    'mi.tartufata':     'Crema de trufa, setas porcini, queso crema, jamón crudo',
    'mi.pinsa':         'Mezcla de harinas especiales, 80% de hidratación, crujiente y ligerísima',
    'mi.tagliere':      'Con gnocco frito y encurtidos',
    'mi.piovra':        'Con crema de parmesano, albahaca y tomatitos cherry confitados',
    'mi.spaghetti':     'Ajo, aceite, guindilla, almejas y tomatitos cherry',
    'mi.tagliata':      'Con rúcula y lascas de Grana Padano',
    'mi.costata':       'A la plancha, aprox. 500 g',
    'mi.paella':        'Bajo reserva',
    'mi.dolci':         'Consultar al personal la propuesta del día',
    'mi.vini':          'Soave classico, Valpolicella, Amarone — selección local',
    'mn.viewFull': 'Ver la carta completa →',
    'mn.note':     'Precios orientativos. La carta completa con todos los detalles está disponible en la página dedicada.',
    'gal.label': 'Momentos del restaurante',
    'gal.h2':    'Nuestra',
    'gal.h2em':  'galería',
    'gal.c1':    'Pizza con burrata y gambas',
    'gal.c2':    'Los ingredientes del día',
    'gal.c3':    'El horno de leña',
    'gal.c4':    'Postres hechos en casa',
    'gal.c5':    'Las colinas del Soave al atardecer',
    'gal.c6':    'Nuestra terraza de verano',
    'ter.label': 'Verano en Costeggiola',
    'ter.h2':    'Cena en la',
    'ter.h2em':  'terraza',
    'ter.lead':  'En los meses más cálidos, disfruta de tu pizza al aire libre en nuestra terraza exterior. Una atmósfera única entre las colinas del Soave, con el aroma del vino y el calor de la cocina artesanal.',
    'ter.btn':   'Reservar tu Mesa',
    'ter.s1':    'Masas artesanales',
    'ter.s2':    'Pizzas en carta',
    'ter.s3':    'Años de experiencia',
    'ter.s4':    'Terraza exterior',
    'rev.label': 'Lo que dicen nuestros clientes',
    'rev.h2':    'Las palabras de',
    'rev.h2em':  'nuestros clientes',
    'rev.q1':    '«La pizza napolitana estaba perfecta — borde alto, ingredientes frescos. Un local auténtico que sabe lo que hace. ¡Volveremos sin duda!»',
    'rev.q2':    '«Por fin una pizzería que se toma en serio el sin gluten. Carta amplia y buenísima. Volveré con toda la familia.»',
    'rev.q3':    '«La pinsa romana es todo un descubrimiento. Ligera y crujiente en su punto justo. Ambiente acogedor, personal amable y profesional.»',
    'rev.ta':    '★ Leer todas las reseñas en TripAdvisor',
    'con.label':  'Encuéntranos',
    'con.h2':     'Dónde estamos &',
    'con.h2em':   'cómo contactarnos',
    'con.phone':  'Teléfono',
    'con.addr':   'Dirección',
    'con.email':  'Correo',
    'con.hours':  'Horario de apertura',
    'con.monTue': 'Lunes – Martes',
    'con.wedFri': 'Miércoles – Viernes',
    'con.sat':    'Sábado',
    'con.sun':    'Domingo',
    'con.closed': 'Cerrado',
    'con.note':   '* Horarios orientativos, llama para confirmar',
    'con.call':   'Llamar ahora',
    'con.today':  'Hoy',
    'con.open':   'Abierto ahora',
    'con.closednow': 'Cerrado ahora',
    'ft.tagline': 'Desde 2002, una cocina que respeta los ingredientes y honra la tradición. En el corazón del Soave.',
    'ft.nav':     'Navegación',
    'ft.follow':  'Síguenos',
    'ft.home':    'Inicio',
    'ft.doughs':  'Nuestras masas',
    'ft.about':   'Quiénes somos',
    'ft.menuFull':'Carta completa',
    'ft.gallery': 'Galería',
    'ft.terrace': 'Terraza',
    'ft.contacts':'Contacto',
    'ft.copy':    '© 2026 Ristorante Pizzeria Corte del Sole · Via Costeggiola 38, Costeggiola (VR)',
    'ft.love':    'Con ♥ en Soave',
    'mh.label':   'Restaurante Pizzería · Costeggiola (VR)',
    'mh.home':    'Inicio',
    'mh.h1':      'Nuestra',
    'mh.h1em':    'carta completa',
    'mh.sub':     'Masas artesanales de fermentación lenta, ingredientes frescos seleccionados y recetas elaboradas con pasión. Desde 2002 en el corazón del Soave.',
    'mh.btnBook': 'Reservar una mesa',
    'mh.btnWa':   'WhatsApp',
    'mt.classiche':   'Clásicas',
    'mt.nostre':      'Nuestras Especialidades',
    'mt.bianche':     'Blancas',
    'mt.glutenfree':  'Sin Gluten',
    'mt.cucina':      'Cocina',
    'mt.insalate':    'Ensaladas',
    'mt.dolci':       'Postres & Bebidas',
    'mt.vini':        'Vinos',
    'ms.1label': '1 — Pizzas',
    'ms.1h2':    'Pizzas',
    'ms.1em':    'Clásicas',
    'ms.1lead':  'La base de nuestro arte — masa napolitana madurada 48 horas, ingredientes seleccionados con cuidado.',
    'ms.2label': '2 — Pizzas de la casa',
    'ms.2h2':    'Nuestras',
    'ms.2em':    'Pizzas Especiales',
    'ms.2lead':  'Creaciones originales nacidas de la fantasía de nuestros pizzeros — cada una cuenta una historia de sabores y territorio.',
    'ms.3label': '3 — Sin salsa de tomate',
    'ms.3h2':    'Pizzas',
    'ms.3em':    'Blancas',
    'ms.3lead':  'Sin salsa de tomate — la base neutra realza quesos, embutidos e ingredientes de excelencia en toda su complejidad.',
    'ms.4label': '4 — Sin Gluten',
    'ms.4h2':    'Pizzas',
    'ms.4em':    'Sin Gluten',
    'ms.4lead':  'No es una concesión — es una opción elaborada con cuidado para quienes tienen intolerancia al gluten. El mismo sabor, el mismo cuidado.',
    'ms.4info':  '<strong>Masa SCHAR</strong> · harina de arroz, almidón de patata, harina de algarroba · naturalmente sin lactosa. La masa sin gluten ya está incluida en el precio indicado.',
    'ms.5label': '5 — Cocina',
    'ms.5h2':    'Nuestra',
    'ms.5em':    'Cocina',
    'ms.5lead':  'Todo elaborado en casa, cada día. De los ingredientes a la mesa, sin compromisos.',
    'ms.5note':  'Cocina abierta mié–dom · 12:00–14:00 y 19:00–22:00',
    'ms.5ant':   'Entrantes',
    'ms.5pri':   'Primeros Platos',
    'ms.5sec':   'Segundos Platos',
    'ms.5baby':  'Menú Infantil',
    'ms.5res':   'Bajo reserva: Paella y Sangría — <strong>28,00 € por persona</strong>',
    'ms.6label': '6 — Ensaladas',
    'ms.6h2':    'Ensaladas Grandes',
    'ms.6em':    '& Guarniciones',
    'ms.6lead':  'Frescas, abundantes, pensadas como plato único — o como acompañamiento perfecto.',
    'ms.6cont':  'Guarniciones',
    'ms.7label': '7 — Postres & Bebidas',
    'ms.7h2':    'Postres, Bebidas',
    'ms.7em':    '& Café',
    'ms.7lead':  'El toque final — nuestros postres hechos en casa cada día, acompañados de cervezas artesanales y café.',
    'ms.7dolci': 'Postres',
    'ms.7bib':   'Bebidas & Cervezas',
    'ms.7caff':  'Café & Digestivos',
    'ms.8label': '8 — Carta de Vinos',
    'ms.8h2':    'Vinos del',
    'ms.8em':    'Territorio',
    'ms.8lead':  'Una selección cuidada de vinos vénetos — Soave, Valpolicella, Amarone — y espumosos locales para acompañar cada comida.',
    'ms.8sp':    'Espumosos',
    'ms.8bi':    'Vinos Blancos',
    'ms.8ro':    'Vinos Tintos',
    'add.title':    'Extras & notas',
    'add.coperto':  'Cubierto',
    'add.box':      'Caja para llevar',
    'add.mini':     'Pizzas mini',
    'add.doppio':   'Doble masa',
    'add.patate':   'Patatas fritas',
    'note.allerg':  '<strong>Alérgenos</strong> — Nuestros alimentos pueden contener alérgenos. Por favor, informe al personal de cualquier alergia o intolerancia alimentaria antes de pedir. Estamos encantados de adaptar vuestra experiencia.',
    'note.orari':   '<strong>Horario cocina</strong> — 12:00–14:00 y 19:00–22:00 · La cocina puede cerrar antes a discreción del personal.',
    'note.prezzi':  '<strong>Precios</strong> — Los precios indicados son orientativos. La carta y los precios pueden variar sin previo aviso. Consulte la carta en sala para precios actualizados.',
    'fm.col':    'La Carta',
    'fm.home':   'Volver al inicio',
    'fm.cont':   'Contacto',
  }
};

/* ── INGREDIENTE TRANSLATOR ── */
function translateIngredients(text, lang) {
  if (!text || lang === 'it') return text;
  const dict = ING[lang];
  if (!dict) return text;
  // Sort keys by length DESC to avoid partial replacements
  const keys = Object.keys(dict).sort((a, b) => b.length - a.length);
  let result = text;
  for (const key of keys) {
    // Case-insensitive, word-boundary aware
    result = result.replace(new RegExp(key, 'gi'), dict[key]);
  }
  // Capitalize first letter
  return result.charAt(0).toUpperCase() + result.slice(1);
}

/* ── APPLY TRANSLATIONS ── */
function t(key, lang) {
  return (T[lang] && T[lang][key]) || (T['it'] && T['it'][key]) || key;
}

function applyLang(lang) {
  document.documentElement.lang = lang === 'it' ? 'it' : lang === 'en' ? 'en' : lang === 'de' ? 'de' : lang === 'fr' ? 'fr' : 'es';

  // Simple text nodes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    el.textContent = t(key, lang);
  });

  // HTML nodes (with em/strong inside)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.dataset.i18nHtml;
    el.innerHTML = t(key, lang);
  });

  // Ingredient descriptions (explicit data-ing OR all .mitem-desc)
  document.querySelectorAll('[data-ing], .mitem-desc').forEach(el => {
    const orig = el.dataset.orig || el.textContent;
    if (!el.dataset.orig) el.dataset.orig = orig;
    el.textContent = translateIngredients(orig, lang);
  });

  // Update selector display
  const cur = document.querySelector('.lang-current-flag');
  const curCode = document.querySelector('.lang-current-code');
  if (cur) cur.textContent = LANGS.find(l => l.code === lang)?.flag || '🇮🇹';
  if (curCode) curCode.textContent = lang.toUpperCase();

  // Mark active option
  document.querySelectorAll('.lang-option').forEach(opt => {
    opt.classList.toggle('active', opt.dataset.lang === lang);
  });

  // Dynamic status badge
  const badge = document.getElementById('statusBadge');
  if (badge) {
    const isOpen = badge.classList.contains('status-open');
    badge.innerHTML = '<div class="status-dot"></div>' + (isOpen ? t('con.open', lang) : t('con.closednow', lang));
  }

  // Dynamic oggi badge
  document.querySelectorAll('.oggi-badge').forEach(b => { b.textContent = t('con.today', lang); });
}

/* ── INJECT SELECTOR UI ── */
function injectSelector() {
  // CSS
  const style = document.createElement('style');
  style.textContent = `
.lang-selector{position:relative;z-index:900;display:flex;align-items:center}
.lang-btn{display:flex;align-items:center;gap:.35rem;background:transparent;
  border:1px solid rgba(255,255,255,.2);color:rgba(255,255,255,.82);
  border-radius:2rem;padding:.32rem .8rem;cursor:pointer;
  font-size:.7rem;font-weight:600;letter-spacing:.07em;
  font-family:var(--body,sans-serif);transition:all .2s;white-space:nowrap}
nav.scrolled .lang-btn{border-color:rgba(24,14,4,.18);color:var(--text-muted,#7A6050)}
.lang-btn:hover{border-color:var(--amber,#C07A10);color:var(--amber,#C07A10)}
.lang-flag{font-size:.95rem;line-height:1}
.lang-drop{position:absolute;top:calc(100% + .6rem);right:0;
  background:var(--soil,#180E04);border:1px solid rgba(255,255,255,.08);
  border-radius:12px;overflow:hidden;min-width:120px;
  box-shadow:0 16px 48px rgba(0,0,0,.5);
  opacity:0;transform:translateY(-8px) scale(.97);
  pointer-events:none;transition:opacity .2s,transform .2s;
  transform-origin:top right}
.lang-selector.open .lang-drop{opacity:1;transform:none;pointer-events:auto}
.lang-option{display:flex;align-items:center;gap:.6rem;
  padding:.6rem 1rem;cursor:pointer;
  font-size:.74rem;color:rgba(255,255,255,.55);
  font-family:var(--body,sans-serif);font-weight:500;
  transition:background .15s,color .15s;white-space:nowrap}
.lang-option:hover{background:rgba(255,255,255,.06);color:rgba(255,255,255,.9)}
.lang-option.active{color:var(--amber,#C07A10)}
.lang-option .lf{font-size:1rem}
`;
  document.head.appendChild(style);

  // HTML — inject before hamburger button
  const nav = document.getElementById('navbar');
  if (!nav) return;

  const sel = document.createElement('div');
  sel.className = 'lang-selector';
  sel.innerHTML = `
<button class="lang-btn" aria-label="Scegli lingua" aria-expanded="false">
  <span class="lang-flag lang-current-flag">🇮🇹</span>
  <span class="lang-current-code">IT</span>
</button>
<div class="lang-drop" role="listbox">
  ${LANGS.map(l => `<div class="lang-option" role="option" data-lang="${l.code}"><span class="lf">${l.flag}</span>${l.label}</div>`).join('')}
</div>`;

  const hbg = document.getElementById('hamburger');
  if (hbg) nav.insertBefore(sel, hbg);
  else nav.appendChild(sel);

  // Events
  const btn = sel.querySelector('.lang-btn');
  btn.addEventListener('click', e => {
    e.stopPropagation();
    const open = sel.classList.toggle('open');
    btn.setAttribute('aria-expanded', open);
  });

  sel.querySelectorAll('.lang-option').forEach(opt => {
    opt.addEventListener('click', () => {
      const lang = opt.dataset.lang;
      localStorage.setItem('cds_lang', lang);
      applyLang(lang);
      sel.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
    });
  });

  document.addEventListener('click', () => {
    sel.classList.remove('open');
    btn.setAttribute('aria-expanded', 'false');
  });
}

/* ── INIT ── */
function init() {
  injectSelector();
  const lang = localStorage.getItem('cds_lang') || 'it';
  applyLang(lang);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}

})();
